// Sample Candidates Data
export const candidatesData = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    position: "Frontend Developer",
    status: "Interview",
    rating: 4.5,
    experience: "3 years",
    phone: "+1-555-0101",
    resume: "john_resume.pdf",
    appliedDate: "2024-03-01",
  },
  {
    id: 2,
    name: "Sarah Smith",
    email: "sarah@example.com",
    position: "UI/UX Designer",
    status: "Shortlisted",
    rating: 4.8,
    experience: "4 years",
    phone: "+1-555-0102",
    resume: "sarah_resume.pdf",
    appliedDate: "2024-03-02",
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike@example.com",
    position: "Backend Engineer",
    status: "Applied",
    rating: 4.2,
    experience: "5 years",
    phone: "+1-555-0103",
    resume: "mike_resume.pdf",
    appliedDate: "2024-03-03",
  },
  {
    id: 4,
    name: "Emma Wilson",
    email: "emma@example.com",
    position: "QA Engineer",
    status: "Rejected",
    rating: 3.8,
    experience: "2 years",
    phone: "+1-555-0104",
    resume: "emma_resume.pdf",
    appliedDate: "2024-03-04",
  },
  {
    id: 5,
    name: "Alex Brown",
    email: "alex@example.com",
    position: "Product Manager",
    status: "Selected",
    rating: 4.9,
    experience: "6 years",
    phone: "+1-555-0105",
    resume: "alex_resume.pdf",
    appliedDate: "2024-03-05",
  },
];

// Sample Jobs Data
export const jobsData = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "Tech Startup Co.",
    location: "Remote",
    salary: "$80k - $120k",
    type: "Full-time",
    description: "Build responsive web applications with React and modern tools",
    requirements: "3+ years experience with React, JavaScript, CSS",
    tags: ["React", "JavaScript", "CSS"],
    skills: ["React", "JavaScript", "CSS"],
    applications: 24,
    postedDate: "2024-02-15",
  },

  {
    id: 2,
    title: "UI/UX Designer",
    company: "Creative Agency",
    location: "New York, NY",
    salary: "$70k - $100k",
    type: "Full-time",
    description: "Design beautiful user-centric digital experiences",
    requirements: "4+ years in UI/UX design, Figma experience",
    tags: ["Figma", "UI Design", "UX"],
    skills: ["Figma", "UI Design", "UX"],
    applications: 18,
    postedDate: "2024-02-20",
  },

  {
    id: 3,
    title: "Backend Engineer",
    company: "Enterprise Solutions",
    location: "Remote",
    salary: "$90k - $130k",
    type: "Full-time",
    description: "Develop scalable backend systems and APIs",
    requirements: "5+ years with Node.js, MongoDB, AWS",
    tags: ["Node.js", "MongoDB", "AWS"],
    applications: 32,
    postedDate: "2024-02-18",
  },
  {
    id: 4,
    title: "QA Engineer",
    company: "Tech Corp",
    location: "Remote",
    salary: "$60k - $90k",
    type: "Contract",
    description: "Ensure software quality through comprehensive testing",
    requirements: "2+ years QA automation experience",
    tags: ["Testing", "Automation", "QA"],
    applications: 15,
    postedDate: "2024-03-01",
  },
  {
    id: 5,
    title: "Data Scientist",
    company: "AI Innovations",
    location: "San Francisco, CA",
    salary: "$100k - $150k",
    type: "Full-time",
    description: "Work with machine learning and data analytics",
    requirements: "3+ years ML experience, Python expert",
    tags: ["Python", "ML", "Data Analysis"],
    applications: 28,
    postedDate: "2024-02-25",
  },
  {
    id: 6,
    title: "Product Manager",
    company: "SaaS Platform",
    location: "Remote",
    salary: "$85k - $125k",
    type: "Full-time",
    description: "Lead product strategy and roadmap development",
    requirements: "4+ years product management experience",
    tags: ["Strategy", "Analytics", "Leadership"],
    applications: 20,
    postedDate: "2024-03-02",
  },
];

// Sample Users (for login)
export const usersData = [
  {
    id: 1,
    email: "recruithubadmin@gmail.com",
    password: "admin123",
    role: "admin",
    name: "Admin User",
    phoneNumber: "",
    qualification: "",
    gender: "",
    dateOfBirth: "",
    address: { city: "", state: "", country: "" },
    professional: {
      currentJobTitle: "",
      currentCompany: "",
      totalExperience: "",
      expectedSalary: "",
      currentSalary: "",
      preferredLocation: "",
      noticePeriod: "",
    },
    education: [],
    skills: { programmingLanguages: [], frameworks: [], databases: [], tools: [] },
    resume: { portfolioLink: "", githubProfile: "", linkedinProfile: "" },
  },
  {
    id: 2,
    email: "user@gmail.com",
    password: "user123",
    role: "user",
    name: "Regular User",
    phoneNumber: "",
    qualification: "",
    gender: "",
    dateOfBirth: "",
    address: { city: "", state: "", country: "" },
    professional: {
      currentJobTitle: "",
      currentCompany: "",
      totalExperience: "",
      expectedSalary: "",
      currentSalary: "",
      preferredLocation: "",
      noticePeriod: "",
    },
    education: [],
    skills: { programmingLanguages: [], frameworks: [], databases: [], tools: [] },
    resume: { portfolioLink: "", githubProfile: "", linkedinProfile: "" },
  },
];
